"use client";

import { useMemo } from "react";
// Assuming these are correct based on the previous context
import { useExcel } from "../context/ExcelContext";
import { EmployeeData } from "../lib/types";

// Define a type for the HR Data that allows dynamic keys generated by the CSV parser.
// This resolves the TypeScript errors without changing the core HRData type in lib/types.
type FlexibleHRData = {
  empCode: string;
  empName: string;
  [key: string]: any; // Allows indexing with dynamic strings like "Unnamed: 8"
};

// --- HELPER FUNCTIONS ---
const canon = (s: string) => (s ?? "").toUpperCase().trim();
const stripNonAlnum = (s: string) => canon(s).replace(/[^A-Z0-9]/g, "");
const numericOnly = (s: string) => (String(s).match(/\d+/g) || []).join("");
const dropLeadingZeros = (s: string) => s.replace(/^0+/, "");
const nameKey = (s: string): string => {
  const cleaned = canon(s).replace(/[^A-Z0-9\s]/g, ""); // Keep spaces
  return cleaned.split(/\s+/).sort().join(""); // Split by space, sort, join
};
// --- END HELPERS ---

/**
 * Hook to create a memoized lookup function for retrieving OT hours from
 * HR data based on employee code or name.
 */
export function useHROTLookup() {
  const { getAllUploadedFiles } = useExcel();

  return useMemo(() => {
    const files = getAllUploadedFiles?.() ?? [];

    // Filter for successfully uploaded Staff and Worker Tulsi files
    const hrFiles = files.filter(
      (f: any) =>
        f.status === "success" &&
        (f.categoryName === "Staff Tulsi" ||
          f.categoryName === "Worker Tulsi") &&
        Array.isArray(f.hrData)
    );

    let employeesWithOtData: any[] = [];

    // CRITICAL REFACTOR: Iterate over files first to apply category-specific column mapping
    for (const file of hrFiles) {
      const isStaff = file.categoryName === "Staff Tulsi";

      if (Array.isArray(file.hrData)) {
        // Debug: Log the first employee's keys to see the structure
        if (file.hrData.length > 0) {
          const firstEmp = file.hrData[0] as FlexibleHRData;
          const allKeys = Object.keys(firstEmp);
          console.log(`\n=== ${isStaff ? "STAFF" : "WORKER"} FILE KEYS ===`);
          console.log("Total columns:", allKeys.length);
          console.log("All keys:", allKeys);
          console.log("Key at index 8:", allKeys[8]);
          console.log("Key at index 5:", allKeys[5]);
          console.log(
            'Keys containing "OT":',
            allKeys.filter((k) => k.includes("OT") || k.includes("ot"))
          );
          console.log("================================\n");
        }

        for (const rawEmp of file.hrData) {
          const emp = rawEmp as FlexibleHRData;
          let otValue: any = 0;

          if (isStaff) {
            // STAFF: Try multiple approaches to find Column I
            otValue =
              emp["Unnamed: 8"] ?? // Approach 1: Unnamed column at position 8
              emp["OT"] ?? // Approach 2: Header name "OT"
              emp["Unnamed: 9"] ?? // Approach 3: Off-by-one fallback
              emp["Unnamed: 7"] ?? // Approach 4: Off-by-one other direction
              0;

            // Debug first few employees
            if (file.hrData.indexOf(rawEmp) < 3) {
              console.log(`Staff ${emp.empCode}:`, {
                "Unnamed: 7": emp["Unnamed: 7"],
                "Unnamed: 8": emp["Unnamed: 8"],
                "Unnamed: 9": emp["Unnamed: 9"],
                OT: emp["OT"],
                Selected: otValue,
              });
            }
          } else {
            // WORKER: Read OT from Column F, including named headers
            const workerKeys = Object.keys(emp);
            const columnFKey = workerKeys[5]; // Column F

            otValue =
              emp[columnFKey] ??
              emp["OT"] ??
              emp["Ot"] ??
              emp["ot"] ??
              emp["OT Hours"] ??
              emp["OT Hrs"] ??
              emp["Overtime"] ??
              emp["Unnamed: 5"] ??
              emp["Unnamed: 6"] ??
              emp["Unnamed: 4"] ??
              0;

            if (file.hrData.indexOf(rawEmp) < 3) {
              console.log(`Worker ${emp.empCode}:`, {
                columnFKey,
                valueAtF: emp[columnFKey],
                OT: emp["OT"],
                "OT Hours": emp["OT Hours"],
                "Unnamed: 5": emp["Unnamed: 5"],
                Selected: otValue,
              });
            }
          }

          const otHours = Number(otValue) || 0;

          employeesWithOtData.push({
            ...emp,
            otHours: otHours,
          });
        }
      }
    }

    if (employeesWithOtData.length === 0) {
      console.log("⚠️ No HR files loaded or hrData is empty for OT lookup");
      return { getHROTValue: () => null };
    }

    console.log(
      `✅ Building HR OT lookup from ${employeesWithOtData.length} total records.`
    );

    const employeeByCode = new Map<string, number>();
    const employeeByName = new Map<string, number>();

    // Now populate the lookup maps using the standardized 'otHours' field
    for (const emp of employeesWithOtData) {
      // The otHours is already correctly extracted and standardized to the Column I/F value
      const otHours = emp.otHours;

      if (emp.empCode) {
        const codeStr = String(emp.empCode);
        const codeKey = stripNonAlnum(codeStr);
        const numKey = numericOnly(codeStr);
        const numKeyStripped = dropLeadingZeros(numKey);

        employeeByCode.set(codeKey, otHours);
        if (numKey) employeeByCode.set(numKey, otHours);
        if (numKeyStripped) employeeByCode.set(numKeyStripped, otHours);
      }

      if (emp.empName) {
        const nKey = nameKey(emp.empName);
        if (nKey) employeeByName.set(nKey, otHours);
      }
    }

    /**
     * Retrieves the OT hours for an employee using various lookup keys.
     * @param emp Employee object with empCode and empName.
     * @returns OT hours (number) or null if no match is found.
     */
    const getHROTValue = (
      emp: Pick<EmployeeData, "empCode" | "empName">
    ): number | null => {
      const codeStr = String(emp.empCode);
      const nameStr = String(emp.empName);

      const codeKey = stripNonAlnum(codeStr);
      const numKey = numericOnly(codeStr);
      const numKeyStripped = dropLeadingZeros(numKey);
      const nKey = nameKey(nameStr);

      // Lookup priority: Stripped Numeric Code -> Full Numeric Code -> Alphanumeric Code -> Name
      let found = employeeByCode.get(numKeyStripped);
      if (found === undefined) found = employeeByCode.get(numKey);
      if (found === undefined) found = employeeByCode.get(codeKey);
      if (found === undefined && nKey) found = employeeByName.get(nKey);

      // Return the found value (which could be 0) or null if not found
      return found ?? null;
    };

    return { getHROTValue };
  }, [getAllUploadedFiles]);
}
